---
# tasks file for poweron
- name: Power on nodes
  community.general.wakeonlan:
    mac: "{{ mac }}" 
  delegate_to: localhost

- name: Wait for server to come up
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ ui_port }}"
  delegate_to: localhost
