---
# defaults file for proxmox_config

proxmox_non_enterprise_subscription: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription

proxmox_packages:
  - sudo
  - libgl1
  - libegl1
  - sysstat
  - htop
  - vim
  - iperf
  - mate
  - chromium
  - lightdm
  - mesa-utils
  - virt-viewer
  - remmina 

disabled_services:
  - lightdm

iso_images: []
#  - https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20220918.3.0/x86_64/fedora-coreos-36.20220918.3.0-live.x86_64.iso
#  - https://download.fedoraproject.org/pub/fedora/linux/releases/test/37_Beta/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-37_Beta-1.5.iso
#  - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Server/x86_64/iso/Fedora-Server-dvd-x86_64-36-1.5.iso

# generate password hash via:
#  mkpasswd --method=sha-512 my_super_secure_password
users:
  - user_name: kmendez
    full_name: "Khary Mendez"
    password: "$6$HhwPB/v5ZmrPbZgP$IgYUvQCZ8fltbw.3QXWKC9juFTh4O/OFyHYT1.535TOOwshlVIBfdg8z2gHyJWIektVqXuEEzoQGZ2F354Xz01"
    groups: "sudo"

external_packages: []
#  - https://download.nomachine.com/download/8.1/Linux/nomachine_8.1.2_1_amd64.deb
