---
# tasks file for shutdown
- name: Unconditionally shut down the server
  community.general.shutdown:

- name: Wait for port to close active connections
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ ui_port }}"
    state: stopped
    timeout: 600
  delegate_to: localhost
